### ISSUE TITLE
gh-pages não funciona as vezes

### ISSUE THREAD

**Issue by amadeu01** [adeonir/simple-boilerplate#1]
Eu vi que tem uma issue aberta do gh-pages.
Com um  [pull request](https://github.com/shinnn/gulp-gh-pages/pull/117)
Mas, até lá, o gh-pages não funciona direito, forcei um update da lib que deu problema `gift` para 0.10.1

Mas, talvez, fosse legal tu colocar uma obsercação no Readme. Ou, deixar a issue. Eu acho que se tiver um tempo vou mandar outro pull request para os caras do gh-pages 😄

**Comment by adeonir** [comment]
Pois é... confesso que usei uma vez pra testar e funcionou de boas.
Pode ver que essas duas issues são mais recentes que meu commit, então eu nem estava sabendo.
Acredito que devam resolver logo, então nem vou fazer essa observação no readme.

Mas valeu pela dica.
